Resources:
  CDKDE331439:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Health API
      EndpointConfiguration:
        Types:
          - EDGE
      Name: CDK
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Resource
  CDKCloudWatchRole73B0CD1F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: cdk-stack/CDK/CloudWatchRole/Resource
  CDKAccount2F865C0D:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - CDKCloudWatchRole73B0CD1F
          - Arn
    DependsOn:
      - CDKDE331439
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Account
  CDKDeployment4B9C8531fbc1b0cef7a137f257f9c88ba1785883:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: CDKDE331439
      Description: Automatically created by the RestApi construct
    DependsOn:
      - CDKauthloginPOST8DE2E5D6
      - CDKauthloginE84AD8F3
      - CDKauth225E94E5
      - CDKauthsignupPOSTC7D884DC
      - CDKauthsignup52AF6079
      - CDKGET46C46C59
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Deployment/Resource
  CDKDeploymentStageprod2FC93819:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: CDKDE331439
      DeploymentId:
        Ref: CDKDeployment4B9C8531fbc1b0cef7a137f257f9c88ba1785883
      StageName: prod
    DependsOn:
      - CDKAccount2F865C0D
    Metadata:
      aws:cdk:path: cdk-stack/CDK/DeploymentStage.prod/Resource
  CDKGETApiPermissioncdkstackCDKE9F930B7GETFBF8D451:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hello26396490
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /
            - Ref: CDKDeploymentStageprod2FC93819
            - /GET/
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/GET/ApiPermission.cdkstackCDKE9F930B7.GET..
  CDKGETApiPermissionTestcdkstackCDKE9F930B7GET8C76BBD6:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - hello26396490
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/GET/ApiPermission.Test.cdkstackCDKE9F930B7.GET..
  CDKGET46C46C59:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - CDKDE331439
          - RootResourceId
      RestApiId:
        Ref: CDKDE331439
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:ap-south-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - hello26396490
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/GET/Resource
  CDKauth225E94E5:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - CDKDE331439
          - RootResourceId
      PathPart: auth
      RestApiId:
        Ref: CDKDE331439
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/Resource
  CDKauthsignup52AF6079:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: CDKauth225E94E5
      PathPart: signup
      RestApiId:
        Ref: CDKDE331439
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/signup/Resource
  CDKauthsignupPOSTApiPermissioncdkstackCDKE9F930B7POSTauthsignupE29CBD96:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - healthNestedStackhealthNestedStackResourceE3347E41
          - Outputs.cdkstackhealthSignup48EA3D8EArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /
            - Ref: CDKDeploymentStageprod2FC93819
            - /POST/auth/signup
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/signup/POST/ApiPermission.cdkstackCDKE9F930B7.POST..auth.signup
  CDKauthsignupPOSTApiPermissionTestcdkstackCDKE9F930B7POSTauthsignup43B38FBA:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - healthNestedStackhealthNestedStackResourceE3347E41
          - Outputs.cdkstackhealthSignup48EA3D8EArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /test-invoke-stage/POST/auth/signup
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/signup/POST/ApiPermission.Test.cdkstackCDKE9F930B7.POST..auth.signup
  CDKauthsignupPOSTC7D884DC:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: CDKauthsignup52AF6079
      RestApiId:
        Ref: CDKDE331439
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:ap-south-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - healthNestedStackhealthNestedStackResourceE3347E41
                  - Outputs.cdkstackhealthSignup48EA3D8EArn
              - /invocations
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/signup/POST/Resource
  CDKauthloginE84AD8F3:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: CDKauth225E94E5
      PathPart: login
      RestApiId:
        Ref: CDKDE331439
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/login/Resource
  CDKauthloginPOSTApiPermissioncdkstackCDKE9F930B7POSTauthlogin03C43DC9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - healthNestedStackhealthNestedStackResourceE3347E41
          - Outputs.cdkstackhealthlogin89D3030EArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /
            - Ref: CDKDeploymentStageprod2FC93819
            - /POST/auth/login
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/login/POST/ApiPermission.cdkstackCDKE9F930B7.POST..auth.login
  CDKauthloginPOSTApiPermissionTestcdkstackCDKE9F930B7POSTauthloginDDDF93D0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - healthNestedStackhealthNestedStackResourceE3347E41
          - Outputs.cdkstackhealthlogin89D3030EArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:ap-south-1:528026266520:"
            - Ref: CDKDE331439
            - /test-invoke-stage/POST/auth/login
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/login/POST/ApiPermission.Test.cdkstackCDKE9F930B7.POST..auth.login
  CDKauthloginPOST8DE2E5D6:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: CDKauthloginE84AD8F3
      RestApiId:
        Ref: CDKDE331439
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:ap-south-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - healthNestedStackhealthNestedStackResourceE3347E41
                  - Outputs.cdkstackhealthlogin89D3030EArn
              - /invocations
    Metadata:
      aws:cdk:path: cdk-stack/CDK/Default/auth/login/POST/Resource
  helloServiceRole353607D3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: cdk-stack/hello/ServiceRole/Resource
  hello26396490:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddS3Bucket29754E0B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddS3VersionKeyE92B6C66
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddS3VersionKeyE92B6C66
      Role:
        Fn::GetAtt:
          - helloServiceRole353607D3
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      FunctionName: hello
      Handler: index.main
      MemorySize: 128
      Runtime: nodejs14.x
      Timeout: 5
    DependsOn:
      - helloServiceRole353607D3
    Metadata:
      aws:cdk:path: cdk-stack/hello/Resource
      aws:asset:path: /home/vatsal/Desktop/cdk-typescript-lambda/cdk.out/asset.da481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbdd
      aws:asset:is-bundled: true
      aws:asset:property: Code
  healthNestedStackhealthNestedStackResourceE3347E41:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
          - ""
          - - https://s3.ap-south-1.
            - Ref: AWS::URLSuffix
            - /
            - Ref: AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875S3Bucket867DD81D
            - /
            - Fn::Select:
                - 0
                - Fn::Split:
                    - "||"
                    - Ref: AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875S3VersionKey94BDEEBD
            - Fn::Select:
                - 1
                - Fn::Split:
                    - "||"
                    - Ref: AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875S3VersionKey94BDEEBD
      Parameters:
        referencetocdkstackAssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3Bucket353CA85CRef:
          Ref: AssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3Bucket7A219AE8
        referencetocdkstackAssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3VersionKeyC2D797C5Ref:
          Ref: AssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3VersionKey14F4DC1F
        referencetocdkstackAssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3Bucket30DC93D0Ref:
          Ref: AssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3Bucket7577BD14
        referencetocdkstackAssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3VersionKey96E5185FRef:
          Ref: AssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3VersionKey697E1C00
        referencetocdkstackAssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3Bucket53399348Ref:
          Ref: AssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3BucketD3230C10
        referencetocdkstackAssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3VersionKeyDA797FDERef:
          Ref: AssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3VersionKeyE030CEFE
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: cdk-stack/health.NestedStack/health.NestedStackResource
      aws:asset:path: cdkstackhealth7D5900AE.nested.template.json
      aws:asset:property: TemplateURL
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1VQ207DMAz9lr2nHhU38UY3xBsXjS8wqenSNkkVO0xT1X8n6VoET+fYx/axXUJ5+wBXm0c8caHrbjtqHwjGD0Hdqf2Xe4syRFEVM0lKNsY1au8dS4hacsE7BrQkFHLw23Yg9jFomlQePOJgGhQ64RnGJEk1mKVqpZXWPjpRTzT0/mzJzcP/RNmcFo9EVoMdMqkXkqOvs7iwVf2/ikGb7H1/SSecVI/2s0YY8yEUrGE23mX5OTotia8lhfM1tQyvM6yq4usC82sY5g+lGHZRdyR5r2lSuQta3n6XN1Dew92mZWOKkC41luBwwR8Fxx3shQEAAA==
    Metadata:
      aws:cdk:path: cdk-stack/CDKMetadata/Default
Outputs:
  CDKEndpoint25D2AB48:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: CDKDE331439
          - .execute-api.ap-south-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: CDKDeploymentStageprod2FC93819
          - /
Parameters:
  AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddS3Bucket29754E0B:
    Type: String
    Description: S3 bucket for asset "da481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbdd"
  AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddS3VersionKeyE92B6C66:
    Type: String
    Description: S3 key for asset version "da481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbdd"
  AssetParametersda481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbddArtifactHashD0089649:
    Type: String
    Description: Artifact hash for asset "da481aa73b9b513df7a4c2cfab91875e73e2f605fa443f1cbfed15ad8119dbdd"
  AssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3Bucket7A219AE8:
    Type: String
    Description: S3 bucket for asset "132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2"
  AssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2S3VersionKey14F4DC1F:
    Type: String
    Description: S3 key for asset version "132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2"
  AssetParameters132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2ArtifactHashEBF670A8:
    Type: String
    Description: Artifact hash for asset "132db0ac22079cb8d1d1260a7fd7b2148448e29c57a9878fdc6731908a274ca2"
  AssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3Bucket7577BD14:
    Type: String
    Description: S3 bucket for asset "bbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1f"
  AssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fS3VersionKey697E1C00:
    Type: String
    Description: S3 key for asset version "bbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1f"
  AssetParametersbbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1fArtifactHashB5C113EE:
    Type: String
    Description: Artifact hash for asset "bbfd37193fb79a232e03c88e6610a1115599bdb51f6bd0ccdba90bb45afccd1f"
  AssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3BucketD3230C10:
    Type: String
    Description: S3 bucket for asset "d05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79"
  AssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79S3VersionKeyE030CEFE:
    Type: String
    Description: S3 key for asset version "d05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79"
  AssetParametersd05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79ArtifactHash7671AE73:
    Type: String
    Description: Artifact hash for asset "d05d00e8ec5d18f1386edf57ee9dbab6608647a1942a1d0ea7740a9fb40eea79"
  AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875S3Bucket867DD81D:
    Type: String
    Description: S3 bucket for asset "5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875"
  AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875S3VersionKey94BDEEBD:
    Type: String
    Description: S3 key for asset version "5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875"
  AssetParameters5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875ArtifactHashF0CEB1C3:
    Type: String
    Description: Artifact hash for asset "5927254bb87a84438d40899c5ebe921a09ff331320cdb81ffd687436bbedd875"

